# Generated by Django 3.1.1 on 2020-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201017_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product Deleted', max_length=200, null=True),
        ),
    ]
